REGION_NAME = "us-east-1"
INSTANCE_TYPE = 't2.micro'
S3_INPUT = "s3-cse546-input-bucket"
S3_OUTPUT = "s3-cse546-output-bucket"
SQS_INPUT = "SQS_Input"
SQS_OUTPUT = "SQS_Output"
KEY = "AAAAAAAAAAAAAAAAA"
KEY_PASS = "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
